import Location as l

class HFood:
    def __init__(self, quantity, name, location, ingredients, health):
        self.quantity = quantity
        self.name = name
        self.location = location
        self.ingredients = ingredients
        self.health = health

#Base food
SweetPotato = HFood(1,"Sweet Potato", [l.Hotel], [], 5)
CurryPowder = HFood(1, "Curry Powder", [l.Uptown], [], 5)
SoySauce = HFood(1, "Soy Sauce", [l.Uptown], [], 5)
OrientalGrass = HFood(1, "Oriental grass", [l.Trail, l.Forest], [], 7)
Burdock = HFood(1, "Burdock", [l.Hotel] , [], 10)
ReliefPatch = HFood(1, "Relief Patch", [l.TownHall], [], 10)
Tuna = HFood(1, "Tuna", [l.Dock], [], 10)
Garlic = HFood(1, "Garlic", [l.Hotel], [], 10)
Potato = HFood(1, "Potato", [l.Hotel], [], 10)
Orange = HFood(5, "Orange", [l.Uptown], [], 12)
BandAid = HFood(1, "Band-Aid", [l.Hospital], [], 15)
Cookie = HFood(3, "Cookie", [l.Hotel, l.Random], [], 15)
Antiseptic = HFood(1, "Antiseptic", [l.Hospital], [], 15)
Ramen = HFood(1, "Ramen", [l.Alley, l.Slum], [], 15)
Bread = HFood(2, "Bread", [], [], 20)
Chocolate = HFood(1, "Chocolate", [l.Uptown], [], 20)
Bandage = HFood(2, "Bandage", [l.Hospital], [], 30)
ScorchedRiceSoup = HFood(4, "Scorched Rice Soup", [], [], 40)
Gimbap = HFood(2, "Gimbap", [], [], 70)
FreshSashimi = HFood(1, "Fresh Sashimi", [l.Beach, l.Dock], [], 120)
GrilledEel = HFood(1, "Grilled Eel", [], [], 170)
#Food
Pill = HFood(1, "Pill", [l.Hospital], [OrientalGrass, ScrollsOfDongYi], 60)
OrientalConcotion = HFood(3, "Oriental Concotion", [], [OrientalGrass, BoilingWater], 35)
Curry = HFood(6, "Curry", [], [CurryPowder, BoilingWater], 38)
Bungeoppang = HFood(3, "Bungeoppang", [], [Carp, Bread], 48)
HoneyMedicine = HFood(3, "Honey Medicine", [], [Honey, Pill], 48)
HotRamen = HFood(4, "Hot Ramen", [], [Ramen, BoilingWater], 50)
ChocolatePie = HFood(2, "Chocolate Pie", [], [Chocolate, Bread], 60)
Herb = HFood(2, "Herb", [], [OrientalGrass, Flower], 60)
# Problem with this sort of class making bullshit
HerbalTea = SFood(5, "Herbal Tea", [], [Herb, BoilingWater], 30)
TurtleSoup = HFood(2, "Turtle Soup", [], [TurtleShell, CookingPot], 61)
Acupuncture = HFood(3, "Acupuncture", [], [Needle, ScrollsOfDongYi], 65)
FirstAidKit = HFood(2, "First Aid Kit", [], [Box, Pill], 76)
HerbMedicine = HFood(1, "Herb Medicine", [], [TurtleShell, ScrollsOfDongYi], 200)
GarlicBread = HFood(3, "Garlic Bread", [], [Garlic, Bread], 40)
LiquorBread = HFood(2, "Liquor Bread", [], [Soju, Bread], 40)
StirFriedRamen = HFood(5, "Stir Fried Ramen", [], [FryingPan, Ramen], 43)
MudfishSoup = HFood(4, "Mudfish Soup", [], [Mudfish, CookingPot], 50)
BakedMudfish = HFood(3, "Baked Mudfish", [], [Mudfish, HeatedWhetstone], 50)
SpicyNoodle = HFood(5, "SpicyNoodle", [], [Ramen, SoySauce], 54)
HealingPotion = HFood(4, "Healing Potion", [], [Herb, GlassBottle], 55)
MochaBread = HFood(3, "Mocha Bread", [], [CoffeeLiqueur, Bread], 60)
Sashimi = HFood(6, "Sashimi", [], [SharpKitchenKnife, Tuna], 70)
ChocoPieBox = HFood(2, "Choco Pie Box", [], [ChocolatePie, Box], 70)
BakedSweetPotato = HFood(4, "Baked Sweet Potato", [], [SweetPotato, HeatedWhetstone], 70)
ChocolateChipCookie = HFood(3, "Chocolate Chip Cookie", [], [Chocolate, Cookie], 70)
FishStew = HFood(3, "Fish Stew", [], [Carp, CookingPot], 72)
BakedCarp = HFood(2, "Baked Carp", [], [Carp, HeatedWhetstone], 75)
PickledGarlic = HFood(4, "Pickled Garlic", [], [Garlic, SoySauce], 85)
GlazedSweetPotato = HFood(3, "Glazed Sweet Potato", [], [SweetPotato, Honey], 95)
TunaCan = HFood(2, "Tuna Can", [], [Tuna, Can], 110)
BakedPotato = HFood(2, "Baked Potato", [], [Potato, HeatedWhetstone], 120)
BraisedBurdock = HFood(4, "Braised Burdock", [], [Burdock, SoySauce], 70)
GarlicRamen = HFood(3, "Garlic Ramen", [], [HotRamen, Garlic], 80)
BraisedPotato = HFood(3, "Braised Potato", [], [Potato, SoySauce], 90)
TenTonicsSoup = HFood(2, "Ten Tonics Soup", [], [TurtleSoup, ScrollsOfDongYi], 100)
GrilledTuna = HFood(2, "Grilled Tuna", [], [Tuna, HeatedWhetstone], 120)
BullIntestine = HFood(1, "Bull Intestine", [], [], 1111)
PetalDewPill = HFood(3, "Petal Dew Pull", [], [PowderOfLife, Flower], 140)